lazyHunterLoad.metadata:updateRevisionFromKeyword("$Revision: 277 $")

function lazyHunterLoad.LoadHunterLocalization(locale)

	lazyHunterLocale.enUS.ACTION_TTS.aimed                = "Aimed Shot"
	lazyHunterLocale.enUS.ACTION_TTS.arcane               = "Arcane Shot"
	lazyHunterLocale.enUS.ACTION_TTS.killCommand          = "Kill Command"
	lazyHunterLocale.enUS.ACTION_TTS.aspectBeast          = "Aspect of the Beast"
	lazyHunterLocale.enUS.ACTION_TTS.aspectCheetah        = "Aspect of the Cheetah"
	lazyHunterLocale.enUS.ACTION_TTS.aspectHawk           = "Aspect of the Hawk"
	lazyHunterLocale.enUS.ACTION_TTS.aspectMonkey         = "Aspect of the Monkey"
	lazyHunterLocale.enUS.ACTION_TTS.aspectPack           = "Aspect of the Pack"
	lazyHunterLocale.enUS.ACTION_TTS.aspectWild           = "Aspect of the Wild"
	--add turlewow Aspect of The Wolf
	lazyHunterLocale.enUS.ACTION_TTS.aspectWolf			  = "Aspect of the Wolf"
	lazyHunterLocale.enUS.ACTION_TTS.eotb                 = "Eyes of the Beast"
	lazyHunterLocale.enUS.ACTION_TTS.beastLore            = "Beast Lore"
	lazyHunterLocale.enUS.ACTION_TTS.call                 = "Call Pet"
	lazyHunterLocale.enUS.ACTION_TTS.concussive           = "Concussive Shot"
	lazyHunterLocale.enUS.ACTION_TTS.counter              = "Counterattack"
	lazyHunterLocale.enUS.ACTION_TTS.deterrence           = "Deterrence"
	lazyHunterLocale.enUS.ACTION_TTS.disengage            = "Disengage"
	lazyHunterLocale.enUS.ACTION_TTS.dismiss              = "Dismiss Pet"
	lazyHunterLocale.enUS.ACTION_TTS.distract             = "Distracting Shot"
	lazyHunterLocale.enUS.ACTION_TTS.eagleEye             = "Eagle Eye"
	lazyHunterLocale.enUS.ACTION_TTS.explosiveTrap        = "Explosive Trap"
	lazyHunterLocale.enUS.ACTION_TTS.feed                 = "Feed Pet"
	lazyHunterLocale.enUS.ACTION_TTS.feign                = "Feign Death"
	lazyHunterLocale.enUS.ACTION_TTS.flare                = "Flare"
	lazyHunterLocale.enUS.ACTION_TTS.frostTrap            = "Frost Trap"
	lazyHunterLocale.enUS.ACTION_TTS.freezingTrap         = "Freezing Trap"
	lazyHunterLocale.enUS.ACTION_TTS.immolationTrap       = "Immolation Trap"
	lazyHunterLocale.enUS.ACTION_TTS.intimidate           = "Intimidation"
	lazyHunterLocale.enUS.ACTION_TTS.huntersMark          = "Hunter's Mark"
	lazyHunterLocale.enUS.ACTION_TTS.mend                 = "Mend Pet"
	lazyHunterLocale.enUS.ACTION_TTS.mongoose             = "Mongoose Bite"
	lazyHunterLocale.enUS.ACTION_TTS.multi                = "Multi-Shot"
	lazyHunterLocale.enUS.ACTION_TTS.raptor               = "Raptor Strike"
	lazyHunterLocale.enUS.ACTION_TTS.rapidFire            = "Rapid Fire"
	lazyHunterLocale.enUS.ACTION_TTS.revive               = "Revive Pet"
	lazyHunterLocale.enUS.ACTION_TTS.scare                = "Scare Beast"
	lazyHunterLocale.enUS.ACTION_TTS.scatter              = "Scatter Shot"
	lazyHunterLocale.enUS.ACTION_TTS.scorpid              = "Scorpid Sting"
	lazyHunterLocale.enUS.ACTION_TTS.serpent              = "Serpent Sting"
	lazyHunterLocale.enUS.ACTION_TTS.steady               = "Steady Shot"
	lazyHunterLocale.enUS.ACTION_TTS.tame                 = "Tame Beast"
	lazyHunterLocale.enUS.ACTION_TTS.trackBeasts          = "Track Beasts"
	lazyHunterLocale.enUS.ACTION_TTS.trackDemons          = "Track Demons"
	lazyHunterLocale.enUS.ACTION_TTS.trackDragonkin       = "Track Dragonkin"
	lazyHunterLocale.enUS.ACTION_TTS.trackElementals      = "Track Elementals"
	lazyHunterLocale.enUS.ACTION_TTS.trackGiants          = "Track Giants"
	lazyHunterLocale.enUS.ACTION_TTS.trackHidden          = "Track Hidden"
	lazyHunterLocale.enUS.ACTION_TTS.trackHumanoids       = "Track Humanoids"
	lazyHunterLocale.enUS.ACTION_TTS.trackUndead          = "Track Undead"
	lazyHunterLocale.enUS.ACTION_TTS.train                = "Beast Training"
	lazyHunterLocale.enUS.ACTION_TTS.tranquilizing        = "Tranquilizing Shot"
	lazyHunterLocale.enUS.ACTION_TTS.trueshot             = "Trueshot Aura"
	lazyHunterLocale.enUS.ACTION_TTS.viper                = "Viper Sting"
	lazyHunterLocale.enUS.ACTION_TTS.volley               = "Volley"
	lazyHunterLocale.enUS.ACTION_TTS.wingClip             = "Wing Clip"
	lazyHunterLocale.enUS.ACTION_TTS.bestialWrath         = "Bestial Wrath"
	lazyHunterLocale.enUS.ACTION_TTS.wyvern               = "Wyvern Sting"

	lazyHunterLocale.enUS.ACTION_TTS.petBite              = "Bite"
	lazyHunterLocale.enUS.ACTION_TTS.petBreath            = "Lightning Breath"
	lazyHunterLocale.enUS.ACTION_TTS.petCharge            = "Charge"
	lazyHunterLocale.enUS.ACTION_TTS.petClaw              = "Claw"
	lazyHunterLocale.enUS.ACTION_TTS.petCower             = "Cower"
	lazyHunterLocale.enUS.ACTION_TTS.petDash              = "Dash"
	lazyHunterLocale.enUS.ACTION_TTS.petDive              = "Dive"
	lazyHunterLocale.enUS.ACTION_TTS.petGrowl             = "Growl"
	lazyHunterLocale.enUS.ACTION_TTS.petHowl              = "Furious Howl"
	lazyHunterLocale.enUS.ACTION_TTS.petPoison            = "Scorpid Poison"
	lazyHunterLocale.enUS.ACTION_TTS.petProwl             = "Prowl"
	lazyHunterLocale.enUS.ACTION_TTS.petScreech           = "Screech"
	lazyHunterLocale.enUS.ACTION_TTS.petShell             = "Shell Shield"
	lazyHunterLocale.enUS.ACTION_TTS.petStomp             = "Thunder Stomp"
	lazyHunterLocale.enUS.ACTION_TTS.petUnprowl           = "Stop Prowling"

	-- LazyHunter.lua
	HUNTER_ADDON_LOADED = " loaded. Powered by "

	-- ParseHunter.lua
	HUNTER_DONT_HAVE_PET_ACTION_BAR = "You do not have a pet action bar."
	HUNTER_INITIATING_AUTO_SHOT = "Initiating auto-shot..."
	HUNTER_INITIATING_AUTO_ATTACK = "Initiating auto-attack..."

	function lazyHunter.CustomLocaleHelp() return [[<H2>Hunter Criteria:</H2>]] end

	if (locale == "zhCN") then
		lazyHunterLocale.zhCN.ACTION_TTS.aimed                = "瞄准射击"
		lazyHunterLocale.zhCN.ACTION_TTS.arcane               = "奥术射击"
		lazyHunterLocale.zhCN.ACTION_TTS.killCommand          = "击杀命令"
		lazyHunterLocale.zhCN.ACTION_TTS.aspectBeast          = "野兽守护"
		lazyHunterLocale.zhCN.ACTION_TTS.aspectCheetah        = "猎豹守护"
		lazyHunterLocale.zhCN.ACTION_TTS.aspectHawk           = "雄鹰守护"
		lazyHunterLocale.zhCN.ACTION_TTS.aspectMonkey         = "灵猴守护"
		lazyHunterLocale.zhCN.ACTION_TTS.aspectPack           = "豹群守护"
		lazyHunterLocale.zhCN.ACTION_TTS.aspectWild           = "野性守护"
		lazyHunterLocale.zhCN.ACTION_TTS.aspectWolf			  = "孤狼守护"
		lazyHunterLocale.zhCN.ACTION_TTS.eotb                 = "野兽之眼"
		lazyHunterLocale.zhCN.ACTION_TTS.beastLore            = "野兽知识"
		lazyHunterLocale.zhCN.ACTION_TTS.call                 = "召唤宠物"
		lazyHunterLocale.zhCN.ACTION_TTS.concussive           = "震荡射击"
		lazyHunterLocale.zhCN.ACTION_TTS.counter              = "反击"
		lazyHunterLocale.zhCN.ACTION_TTS.deterrence           = "威慑"
		lazyHunterLocale.zhCN.ACTION_TTS.disengage            = "逃脱"
		lazyHunterLocale.zhCN.ACTION_TTS.dismiss              = "解散野兽"
		lazyHunterLocale.zhCN.ACTION_TTS.distract             = "扰乱射击"
		lazyHunterLocale.zhCN.ACTION_TTS.eagleEye             = "鹰眼术"
		lazyHunterLocale.zhCN.ACTION_TTS.explosiveTrap        = "爆炸陷阱"
		lazyHunterLocale.zhCN.ACTION_TTS.feed                 = "喂养宠物"
		lazyHunterLocale.zhCN.ACTION_TTS.feign                = "假死"
		lazyHunterLocale.zhCN.ACTION_TTS.flare                = "照明弹"
		lazyHunterLocale.zhCN.ACTION_TTS.frostTrap            = "冰霜陷阱"
		lazyHunterLocale.zhCN.ACTION_TTS.freezingTrap         = "冰冻陷阱"
		lazyHunterLocale.zhCN.ACTION_TTS.immolationTrap       = "献祭陷阱"
		lazyHunterLocale.zhCN.ACTION_TTS.intimidate           = "胁迫"
		lazyHunterLocale.zhCN.ACTION_TTS.huntersMark          = "猎人印记"
		lazyHunterLocale.zhCN.ACTION_TTS.mend                 = "治疗宠物"
		lazyHunterLocale.zhCN.ACTION_TTS.mongoose             = "猫鼬撕咬"
		lazyHunterLocale.zhCN.ACTION_TTS.multi                = "多重射击"
		lazyHunterLocale.zhCN.ACTION_TTS.raptor               = "猛禽一击"
		lazyHunterLocale.zhCN.ACTION_TTS.rapidFire            = "急速射击"
		lazyHunterLocale.zhCN.ACTION_TTS.revive               = "复活宠物"
		lazyHunterLocale.zhCN.ACTION_TTS.scare                = "恐吓野兽"
		lazyHunterLocale.zhCN.ACTION_TTS.scatter              = "驱散射击"
		lazyHunterLocale.zhCN.ACTION_TTS.scorpid              = "毒蝎钉刺"
		lazyHunterLocale.zhCN.ACTION_TTS.serpent              = "毒蛇钉刺"
		lazyHunterLocale.enUS.ACTION_TTS.steady               = "稳固射击"
		lazyHunterLocale.zhCN.ACTION_TTS.tame                 = "驯服野兽"
		lazyHunterLocale.zhCN.ACTION_TTS.trackBeasts          = "追踪野兽"
		lazyHunterLocale.zhCN.ACTION_TTS.trackDemons          = "追踪恶魔"
		lazyHunterLocale.zhCN.ACTION_TTS.trackDragonkin       = "追踪龙类"
		lazyHunterLocale.zhCN.ACTION_TTS.trackElementals      = "追踪元素生物"
		lazyHunterLocale.zhCN.ACTION_TTS.trackGiants          = "追踪巨人"
		lazyHunterLocale.zhCN.ACTION_TTS.trackHidden          = "追踪隐藏生物"
		lazyHunterLocale.zhCN.ACTION_TTS.trackHumanoids       = "追踪人型生物"
		lazyHunterLocale.zhCN.ACTION_TTS.trackUndead          = "追踪亡灵"
		lazyHunterLocale.zhCN.ACTION_TTS.train                = "训练野兽"
		lazyHunterLocale.zhCN.ACTION_TTS.tranquilizing        = "宁神射击"
		lazyHunterLocale.zhCN.ACTION_TTS.trueshot             = "强击光环"
		lazyHunterLocale.zhCN.ACTION_TTS.viper                = "蝰蛇钉刺"
		lazyHunterLocale.zhCN.ACTION_TTS.volley               = "乱射"
		lazyHunterLocale.zhCN.ACTION_TTS.wingClip             = "摔绊"
		lazyHunterLocale.zhCN.ACTION_TTS.bestialWrath         = "狂野怒火"
		lazyHunterLocale.zhCN.ACTION_TTS.wyvern               = "翼龙钉刺"

		lazyHunterLocale.zhCN.ACTION_TTS.petBite              = "撕咬"
		lazyHunterLocale.zhCN.ACTION_TTS.petBreath            = "闪电吐息"
		lazyHunterLocale.zhCN.ACTION_TTS.petCharge            = "冲锋"
		lazyHunterLocale.zhCN.ACTION_TTS.petClaw              = "爪击"
		lazyHunterLocale.zhCN.ACTION_TTS.petCower             = "畏缩"
		lazyHunterLocale.zhCN.ACTION_TTS.petDash              = "突进"
		lazyHunterLocale.zhCN.ACTION_TTS.petDive              = "俯冲"
		lazyHunterLocale.zhCN.ACTION_TTS.petGrowl             = "低吼"
		lazyHunterLocale.zhCN.ACTION_TTS.petHowl              = "狂怒之嚎"
		lazyHunterLocale.zhCN.ACTION_TTS.petPoison            = "蝎毒"
		lazyHunterLocale.zhCN.ACTION_TTS.petProwl             = "潜伏"
		lazyHunterLocale.zhCN.ACTION_TTS.petScreech           = "尖啸"
		lazyHunterLocale.zhCN.ACTION_TTS.petShell             = "甲壳护盾"
		lazyHunterLocale.zhCN.ACTION_TTS.petStomp             = "雷霆践踏"
		lazyHunterLocale.zhCN.ACTION_TTS.petUnprowl           = "Stop Prowling" --待确认
	end
end
